### PR TITLE
Rewrote the LineParser to create as few intermediate objects as possible

### PR DESCRIPTION
**Pull request by viktorklang**

### CODE REVIEW

**Comment by hseeberger** [comment]
Nice. I'll run some benchmarks to see whether it's worth to obfuscate the code that way ;-)

**Comment by viktorklang** [comment]
@hseeberger Lol, I actually find the new version more readable (less ad-hoc data structures) :)

**Comment by hseeberger** [comment]
@viktorklang, I think you might have specialized too much for the average developer ;-)

**Comment by viktorklang** [comment]
@hseeberger Not surprisingly, I disagree. There was a lot more going on in the original code, minor hacks (appending a NUL-byte to the ByteString), intermediate ad-hoc data structures, multiple collection transformations etc.

The new implementation does a single-pass over the ByteString, looks at the individual bytes, does lookahead for CRLF, does backtracking to discard CR after CRLF. :)

**Comment by hseeberger** [comment]
You name it: backtracking. But I'll give it a fair chance once I have some spare cycles ;-)

**Comment by viktorklang** [comment]
@hseeberger Well, it only backtracks 1 step back, and only if it encounters a CR. The old implementation creates heap objects for the backtracking. :)
(I did originally also have a boolean parameter to indicate if there was a CRLF previously, in case you are worried about performance of accessing already fetched memory ;))

**Comment by hseeberger** [comment]
@viktorklang, you're my hero. You have always been, but now it's official.
Before: `LineParserBenchmark.benchmark             thrpt   20   3.555 ± 0.097  ops/s`
After your PR: `LineParserBenchmark.benchmark             thrpt   20  12.201 ± 0.285  ops/s`
So your PR makes the `LineParser` more than 3 times faster!

**Comment by viktorklang** [comment]
@hseeberger Thanks for the kind words, Heiko, thanks for letting me contribute to this fine project! :)

**Pull request merged**
