### PR TITLE
Reducing memory usage and indirection for LineParser

### PR DESCRIPTION
**Pull request by viktorklang**

### CODE REVIEW

**Comment by hseeberger** [comment]
Could you please explain the benefits?

**Comment by viktorklang** [comment]
@hseeberger Not having to allocate separate memory for the handlers means less pointer-chasing which means less memory usage (object headers and captured fields) and less indirection (faster calls)

**Comment by hseeberger** [comment]
Oh, really? Well, quite subtle optimization. Thanks for sharing this knowledge!

**Comment by viktorklang** [comment]
@hseeberger Since my PR doesn't change semantics, is this a known flaky test?
https://travis-ci.org/hseeberger/akka-sse/jobs/176000593#L926

**Comment by hseeberger** [comment]
@viktorklang Yes, it's a known flaky one. As the feature is deprecated, I don't worry too much.

**Comment by hseeberger** [comment]
@viktorklang Thanks!

**Comment by viktorklang** [comment]
@hseeberger You're welcome!

**Pull request merged**
